sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=staticlibot
    - secure: "GtElFHDHDc58OS2dnIuOSDo8lpHVkLkTNDcd+oVEFo5C/ZHuW9mP3bZB0+W8/m9FMI09fTdSkG5fzJm6j32Nk8TVcb2UqHH7YQxb42iAmrsaUcA+EUKt1exNVXNZwilOfOMx8KKTZFs777eD6fPwvM3W8bU9Uiz3mk5XWlmF1jJ8/l9N/oAQerLgFNPixHKXY+UEakMceygLzA7kUxo+cH21Aq1i7wemS5JW2OsCABiNB/UWJgt8Lnqew3eotaZwwoLOchltG88EABoZCLLAj/eK0DeD4qObgZMfTxbu+v+xJsdaENAZnUaLXxEkK4xM9KVD4vI3qGAXn8Mp2O1Kg/1nL0u1EcsISOlA3jWCG6Mf/xwbuLKa0DJR3zpEZ4LW5PYATKqziH8f66ioIVtv7gIkz4tH86OGCxFGRp9HXWiDIhnkWIEK3NlvkT7hcgTLn2Q3ZluJaJt7OzthWQG6C5dwZFEE9KJ98/tseZAnnL/gRM/e9PZcpBHgmrCodwFXEPDY8NcOdLx/0Pbv6Ky0q12tLeh6orn+HCQo/CxPHYkCHQ9P62SsyAirxCYsgh1iheS1Gzb9GgPjEkX//W5NaUohBPx/dN4f5PV3QqTL8GrCW4JsVDdv3x1N4CrnTihlLcPrGgoZQ/KdGCEQA0enu58YacQ0BmH164I/A6p3p8k="

script:
  - docker build --tag staticli/proselint .
  - docker run staticli/proselint

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push staticli/proselint
  on:
    branch: master